<?php

namespace AppBundle\Repository;

/**
 * TrailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrailRepository extends \Doctrine\ORM\EntityRepository
{
}
